name: Michel Beloshitsky
description: Web Developer from Russia

url:
baseurl: ""

permalink: /:title/

version: v1.2.0

collections:
  log:
    output: true

markdown: redcarpet

sass:
  sass_dir: _sass
  style: :expanded

plugins:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
